import { Link, useParams } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Clock, MapPin, XCircle } from "lucide-react";
import { toast } from "sonner";
import AppShell, { RequireAuth } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { apiGet, apiPost } from "@/lib/api";
import { useSession } from "@/lib/session";
import type { Attendance, ClubEvent, EventDetail, Player } from "@/lib/types";
export function EventsPage() {
  const { user, isLoading } = useSession();
  const events = useQuery<ClubEvent[]>({ queryKey: ["events"], enabled: !!user, queryFn: () => apiGet<ClubEvent[]>("/events") });
  return (<AppShell><RequireAuth user={user} isLoading={isLoading}>
    <h1 className="font-heading text-3xl font-black uppercase tracking-tighter">Schedule</h1>
    <div className="mt-6 space-y-3" data-testid="events-list">{events.isLoading ? <p className="text-sm text-muted-foreground">Loading…</p> : (events.data ?? []).length === 0 ? <p className="text-sm text-muted-foreground" data-testid="events-empty">No events scheduled.</p> : (events.data ?? []).map((e) => (<Link key={e.id} to={`/events/${e.id}`} data-testid={`event-card-${e.id}`} className="block rounded-xl border border-border bg-card p-5 transition-colors hover:border-crimson/40"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Badge variant="outline" className="uppercase">{e.kind}</Badge>{e.fee_label ? <Badge className="border-crimson/40 bg-crimson-soft text-crimson-bright">{e.fee_label}</Badge> : null}</div><p className="mt-2 font-heading text-lg font-semibold">{e.title}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><MapPin className="size-3" />{e.location} · {e.org_name}</p><p className="mt-2 font-mono text-xs text-crimson-bright">{new Date(e.starts_at).toLocaleString("en-CA", { dateStyle: "full", timeStyle: "short", timeZone: e.venue_timezone })}</p></div><div className="text-right font-mono text-xs"><p className="text-pitch">{e.confirmed_in} in</p><p className="text-destructive">{e.confirmed_out} out</p><p className="text-muted-foreground">{e.no_response} no response</p></div></div></Link>))}
    </div>
  </RequireAuth></AppShell>);
}
export function EventDetailPage() {
  const { eventId = "" } = useParams(); const { user, isLoading } = useSession(); const qc = useQueryClient();
  const detail = useQuery<EventDetail>({ queryKey: ["events", eventId], enabled: !!user && !!eventId, queryFn: () => apiGet<EventDetail>(`/events/${eventId}`) });
  const players = useQuery<Player[]>({ queryKey: ["players"], enabled: !!user, queryFn: () => apiGet<Player[]>("/players") });
  const rsvp = useMutation({ mutationFn: (payload: { player_id: string; status: "in" | "out" }) => apiPost<Attendance>(`/events/${eventId}/rsvp`, payload), onSuccess: (record) => { qc.invalidateQueries({ queryKey: ["events"] }); toast.success(`${record.player_name} marked ${record.status === "in" ? "available" : "unavailable"}`); }, onError: () => toast.error("Could not record that RSVP") });
  const event = detail.data?.event; const rows = detail.data?.attendance ?? []; const canRsvp = user?.role === "guardian" || user?.role === "admin"; const myPlayers = players.data ?? [];
  return (<AppShell><RequireAuth user={user} isLoading={isLoading}>{!event ? <p className="py-16 text-center text-sm text-muted-foreground">Loading…</p> : (<><Link to="/events" className="text-xs text-muted-foreground hover:text-crimson-bright">← All events</Link><h1 className="mt-3 font-heading text-3xl font-black uppercase tracking-tighter" data-testid="event-detail-title">{event.title}</h1><p className="mt-2 text-sm text-muted-foreground">{event.location} · {new Date(event.starts_at).toLocaleString("en-CA", { dateStyle: "full", timeStyle: "short", timeZone: event.venue_timezone })}</p>
  {canRsvp && myPlayers.length > 0 ? (<Card className="mt-6 border-crimson/30" data-testid="rsvp-panel"><CardContent className="p-5"><p className="font-heading text-sm font-semibold">One-tap RSVP</p><div className="mt-4 space-y-3">{myPlayers.map((p) => { const current = rows.find((r) => r.player_id === p.id)?.status ?? "no_response"; return (<div key={p.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border p-3"><span className="text-sm font-medium">#{p.jersey_no} {p.full_name} <span className="ml-2 font-mono text-[11px] text-muted-foreground">{current.replace("_", " ")}</span></span><div className="flex gap-2"><Button size="sm" className="h-11 min-w-[80px] bg-pitch text-white" onClick={() => rsvp.mutate({ player_id: p.id, status: "in" })} disabled={rsvp.isPending} data-testid={`rsvp-in-${p.id}`}><CheckCircle2 className="mr-1 size-4" /> In</Button><Button size="sm" variant="outline" className="h-11 min-w-[80px]" onClick={() => rsvp.mutate({ player_id: p.id, status: "out" })} disabled={rsvp.isPending} data-testid={`rsvp-out-${p.id}`}><XCircle className="mr-1 size-4" /> Out</Button></div></div>); })}</div></CardContent></Card>) : null}
  <h2 className="mt-10 font-heading text-lg font-bold tracking-tight">Attendance</h2><div className="mt-3 space-y-3">{rows.length === 0 ? <p className="text-sm text-muted-foreground">No records.</p> : rows.map((r) => (<Card key={r.id} className="border-border"><CardContent className="p-4"><div className="flex items-center justify-between"><span className="text-sm font-medium">{r.player_name}</span><Badge variant={r.status === "in" ? "default" : "secondary"}>{r.status.replace("_", " ")}</Badge></div>{r.timestamp_log.length > 0 ? <ul className="mt-3 space-y-1 border-l border-border pl-3">{r.timestamp_log.map((entry, i) => <li key={i} className="flex items-center gap-2 font-mono text-[11px] text-muted-foreground"><Clock className="size-3" />{new Date(entry.changed_at).toLocaleString("en-CA", { dateStyle: "short", timeStyle: "short" })} → {entry.status} · by {entry.changed_by}</li>)}</ul> : null}</CardContent></Card>))}</div></>)}</RequireAuth></AppShell>);
}
