import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Copy, MapPin, Send, UserCheck, X } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { apiDelete, apiGet, apiPost, ApiError } from "@/lib/api";
import type { Coach, CoachInvite, OkResponse, Organization } from "@/lib/types";
function errText(err: unknown, fallback: string) { if (err instanceof ApiError) { const body = err.body as { detail?: unknown } | null; if (typeof body?.detail === "string") return body.detail; } return fallback; }
export default function CoachApplications() {
  const qc = useQueryClient();
  const [target, setTarget] = useState<Coach | null>(null);
  const [orgIds, setOrgIds] = useState<string[]>([]);
  const [pct, setPct] = useState("40");
  const [team, setTeam] = useState("");
  const [inviteOpen, setInviteOpen] = useState(false);
  const [inv, setInv] = useState({ name: "", email: "", team_name: "", payout_percentage: "40" });
  const [invOrgs, setInvOrgs] = useState<string[]>([]);
  const invites = useQuery<CoachInvite[]>({ queryKey: ["coach-invites"], queryFn: () => apiGet<CoachInvite[]>("/coach-invites") });
  const apps = useQuery<Coach[]>({ queryKey: ["coach-applications"], queryFn: () => apiGet<Coach[]>("/coach-applications") });
  const orgs = useQuery<Organization[]>({ queryKey: ["organizations"], queryFn: () => apiGet<Organization[]>("/organizations") });
  function refresh(message: string) { qc.invalidateQueries({ queryKey: ["coach-applications"] }); qc.invalidateQueries({ queryKey: ["coaches"] }); setTarget(null); toast.success(message); }
  const approve = useMutation({ mutationFn: () => apiPost<Coach>(`/coach-applications/${target!.id}/approve`, { org_ids: orgIds, payout_percentage: Number(pct), team_name: team }), onSuccess: (c) => refresh(`${c.name} approved`), onError: (e) => toast.error(errText(e, "Could not approve")) });
  const sendInvite = useMutation({ mutationFn: () => apiPost<CoachInvite>("/coach-invites", { ...inv, org_ids: invOrgs, payout_percentage: Number(inv.payout_percentage) }), onSuccess: (created) => { qc.invalidateQueries({ queryKey: ["coach-invites"] }); setInviteOpen(false); setInv({ name: "", email: "", team_name: "", payout_percentage: "40" }); setInvOrgs([]); if (created.email_status === "sent") toast.success(`Invite emailed to ${created.email}`); else { void copyLink(created.token); toast.warning("Invite created — email not sent"); } }, onError: (e) => toast.error(errText(e, "Could not create invite")) });
  const revoke = useMutation({ mutationFn: (id: string) => apiDelete<OkResponse>(`/coach-invites/${id}`), onSuccess: () => { qc.invalidateQueries({ queryKey: ["coach-invites"] }); toast.success("Invite withdrawn"); }, onError: (e) => toast.error(errText(e, "Could not withdraw")) });
  const resend = useMutation({ mutationFn: (id: string) => apiPost<CoachInvite>(`/coach-invites/${id}/resend`), onSuccess: (i) => { qc.invalidateQueries({ queryKey: ["coach-invites"] }); if (i.email_status === "sent") toast.success(`Re-sent to ${i.email}`); else toast.error("Email failed"); }, onError: (e) => toast.error(errText(e, "Could not resend")) });
  const reject = useMutation({ mutationFn: (id: string) => apiPost<OkResponse>(`/coach-applications/${id}/reject`), onSuccess: () => refresh("Rejected"), onError: (e) => toast.error(errText(e, "Could not reject")) });
  async function copyLink(token: string) { const url = `${window.location.origin}/coach-invite/${token}`; try { await navigator.clipboard.writeText(url); toast.success("Link copied"); } catch { toast.info(url); } }
  const rows = apps.data ?? [];
  const OrgToggle = ({ ids, setIds, testPrefix }: { ids: string[]; setIds: (fn: (p: string[]) => string[]) => void; testPrefix: string }) => (<div className="space-y-2">{(orgs.data ?? []).map((o) => { const on = ids.includes(o.id); return (<button key={o.id} type="button" onClick={() => setIds((p) => p.includes(o.id) ? p.filter((x) => x !== o.id) : [...p, o.id])} data-testid={`${testPrefix}-${o.id}`} className={`flex w-full items-center justify-between gap-3 rounded-lg border p-4 text-left transition-colors ${on ? "border-gold bg-gold-soft" : "border-border hover:border-gold/50"}`}><span className="flex items-center gap-2 text-sm"><MapPin className="size-4 shrink-0 text-gold" />{o.name}</span>{on ? <CheckCircle2 className="size-5 shrink-0 text-gold" /> : null}</button>); })}</div>);
  return (<div data-testid="coach-applications">
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="font-heading text-lg font-bold tracking-tight">Invite a coach</p><Button className="h-11 bg-crimson text-white hover:bg-crimson-bright" onClick={() => setInviteOpen(true)} data-testid="coach-invite-open"><Send className="mr-1.5 size-4" /> New invite</Button></div>
    <div className="mt-3 space-y-2" data-testid="coach-invites-list">{(invites.data ?? []).length === 0 ? <p className="text-sm text-muted-foreground" data-testid="coach-invites-empty">No unused invites.</p> : (invites.data ?? []).map((i) => (<Card key={i.id} className="border-border" data-testid={`coach-invite-${i.id}`}><CardContent className="flex flex-wrap items-center gap-3 p-4"><div className="min-w-0 flex-1"><p className="truncate font-heading text-sm font-semibold">{i.name}</p><p className="font-mono text-xs text-muted-foreground">{i.email} · {i.org_names.join(", ")}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" className="h-11" onClick={() => resend.mutate(i.id)} disabled={resend.isPending}><Send className="mr-1.5 size-4" /> Resend</Button><Button size="sm" variant="outline" className="h-11" onClick={() => void copyLink(i.token)}><Copy className="mr-1.5 size-4" /> Copy</Button><Button size="sm" variant="ghost" className="h-11" onClick={() => revoke.mutate(i.id)}><X className="size-4" /></Button></div></CardContent></Card>))}</div>
    <p className="mt-8 font-heading text-lg font-bold tracking-tight">Applications</p>
    <div className="mt-4 space-y-3" data-testid="coach-applications-list">{!apps.isLoading && rows.length === 0 ? <p className="text-sm text-muted-foreground" data-testid="coach-applications-empty">No pending applications.</p> : rows.map((c) => (<Card key={c.id} className="border-border" data-testid={`coach-app-${c.id}`}><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><p className="font-heading text-sm font-semibold">{c.name}</p><p className="font-mono text-xs text-muted-foreground">{c.email}</p>{c.experience ? <p className="mt-2 text-xs text-muted-foreground">{c.experience}</p> : null}</div><div className="flex gap-2"><Button size="sm" className="h-11 bg-crimson text-white hover:bg-crimson-bright" onClick={() => { setTarget(c); setOrgIds(c.org_ids ?? []); setPct("40"); setTeam(c.team_name ?? ""); }} data-testid={`coach-app-approve-${c.id}`}><UserCheck className="mr-1.5 size-4" /> Approve</Button><Button size="sm" variant="outline" className="h-11" onClick={() => reject.mutate(c.id)} data-testid={`coach-app-reject-${c.id}`}>Reject</Button></div></div></CardContent></Card>))}</div>
    <Dialog open={inviteOpen} onOpenChange={setInviteOpen}><DialogContent className="max-h-[85dvh] overflow-y-auto sm:max-w-md"><DialogHeader><DialogTitle className="font-heading uppercase">Invite a coach</DialogTitle><DialogDescription>Creates a single-use link valid for 14 days.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); sendInvite.mutate(); }} data-testid="coach-invite-form"><div className="space-y-2"><Label>Name</Label><Input className="h-12" required value={inv.name} onChange={(e) => setInv({ ...inv, name: e.target.value })} /></div><div className="space-y-2"><Label>Email</Label><Input type="email" className="h-12" required value={inv.email} onChange={(e) => setInv({ ...inv, email: e.target.value })} /></div><div className="space-y-2"><Label>Locations</Label><OrgToggle ids={invOrgs} setIds={setInvOrgs} testPrefix="coach-invite-org" /></div><Button type="submit" className="h-12 w-full bg-crimson text-white hover:bg-crimson-bright" disabled={sendInvite.isPending || !inv.name || !inv.email || invOrgs.length === 0} data-testid="coach-invite-submit">{sendInvite.isPending ? "Creating…" : "Create invite link"}</Button></form></DialogContent></Dialog>
    <Dialog open={target !== null} onOpenChange={(v) => !v && setTarget(null)}><DialogContent className="max-h-[85dvh] overflow-y-auto sm:max-w-md"><DialogHeader><DialogTitle className="font-heading uppercase">Approve {target?.name}</DialogTitle><DialogDescription>Assign locations and set payout.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); approve.mutate(); }} data-testid="coach-approve-form"><div className="space-y-2"><Label>Locations</Label><OrgToggle ids={orgIds} setIds={setOrgIds} testPrefix="coach-approve-org" /></div><div className="space-y-2"><Label>Team</Label><Input className="h-12" value={team} onChange={(e) => setTeam(e.target.value)} /></div><div className="space-y-2"><Label>Payout %</Label><Input type="number" className="h-12" value={pct} onChange={(e) => setPct(e.target.value)} /></div><Button type="submit" className="h-12 w-full bg-crimson text-white hover:bg-crimson-bright" disabled={approve.isPending || orgIds.length === 0} data-testid="coach-approve-submit">{approve.isPending ? "Approving…" : "Approve coach"}</Button></form></DialogContent></Dialog>
  </div>);
}
